version: '3.8'

services:
  app:
    build: ./backend
    container_name: laravel-app
    volumes:
      - ./backend:/var/www/html
    environment:
      APP_ENV: local
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: rootbulb
      DB_USERNAME: localuser
      DB_PASSWORD: Fart-54948323
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: rootbulb
      MYSQL_USER: localuser
      MYSQL_PASSWORD: Fart-54948323
      MYSQL_ROOT_PASSWORD: Fart-54948323
    volumes:
      - db_data:/var/lib/mysql

  composer:
    image: composer:2
    container_name: composer
    volumes:
      - ./backend:/app
    working_dir: /app
    command: install

volumes:
  db_data:
